---
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: ClusterIP
  selector:
    name: front-end
  ports:
  - port: 80
    targetPort: 8079

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: 'nginx'
#   name: frontend-ingress
# spec:
#   rules:
#   - host: sock.dev.youngsjeong.com
#     http:
#       paths:
#       - backend:
#           serviceName: front-end
#           servicePort: 80
#         path: /
