---
apiVersion: v1
kind: Service
metadata:
  metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    external-dns.alpha.kubernetes.io/hostname: sock.youngsjeong.com
  name: front-end
  labels:
    name: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
