---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8079
  selector:
    app: front-end
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'nginx'
  name: frontend-ingress
spec:
  rules:
  - host: sock.youngsjeong.com
    http:
      paths:
      - backend:
          serviceName: front-end
          servicePort: 80
        path: /
